/**************************************************************************/
/* Copyright (c) 2019 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           6519

#define PATCH_ENTRY_CREATE_MUTE_OP               0x04003f49 /* $_create_mute_op */
#define PATCH_ENTRY_CBOPS_MUTE_ENABLE            0x04003f83 /* $_cbops_mute_enable */
#define PATCH_ENTRY_CBOPS_MUTE_RESET             0x04003f89 /* $_cbops_mute_reset */
#define PATCH_ENTRY_TTP_UPDATE_TTP_FROM_SOURCE_TIME 0x04004ea1 /* $_ttp_update_ttp_from_source_time */
#define PATCH_ENTRY_GET_BT_ADDRESS               0x04005131 /* $_get_bt_address */
#define PATCH_ENTRY_SET_LIC_DEBUG                0x04005251 /* $_set_lic_debug */
#define PATCH_ENTRY_EXTMEM_ENABLE                0x0400755b /* $_extmem_enable */
#define PATCH_ENTRY_EXTMEM_ENABLE_WITH_RETRY     0x040075eb /* $_extmem_enable_with_retry */
#define PATCH_ENTRY_EXTMEM_LOCK                  0x04007641 /* $_extmem_lock */
#define PATCH_ENTRY_EXTMEM_UNLOCK                0x0400768b /* $_extmem_unlock */
#define PATCH_ENTRY_EXTMEM_GET_MODE              0x040076bb /* $_extmem_get_mode */
#define PATCH_ENTRY_AUDIO_THREAD_RPC_CALL        0x04007ced /* $_audio_thread_rpc_call */
#define PATCH_ENTRY_AUDIO_THREAD_RPC_IS_ACTIVE   0x04007db7 /* $_audio_thread_rpc_is_active */
#define PATCH_ENTRY_AUDIO_THREAD_GET_RPC_ACTIVE  0x04007dd1 /* $_audio_thread_get_rpc_active */
#define PATCH_ENTRY_AUDIO_THREAD_OFFLOAD_IS_ACTIVE 0x04007de5 /* $_audio_thread_offload_is_active */
#define PATCH_ENTRY_AUDIO_THREAD_OFFLOAD_IS_ENABLED 0x04007e01 /* $_audio_thread_offload_is_enabled */
#define PATCH_ENTRY_AUDIO_THREAD_COPY_FFT_TWIDDLE 0x04007d4f /* $_audio_thread_copy_fft_twiddle */
#define PATCH_ENTRY_AUDIO_THREAD_SET_UP_APTX     0x04007d8b /* $_audio_thread_set_up_aptx_offload */
#define PATCH_ENTRY_CBUFFER_GET_READ_OFFSET_EX   0x040080f7 /* $_cbuffer_get_read_offset_ex */
#define PATCH_ENTRY_CBUFFER_COPY_EX              0x0400811b /* $_cbuffer_copy_ex */
#define PATCH_ENTRY_CBUFFER_GET_USABLE_OCTETS    0x040080d7 /* $_cbuffer_get_usable_octets */
#define PATCH_ENTRY_CBUFFER_SET_USABLE_OCTETS    0x040080eb /* $_cbuffer_set_usable_octets */
#define PATCH_ENTRY_CBUFFER_ADVANCE_WRITE_PTR_EX 0x04009b93 /* $_cbuffer_advance_write_ptr_ex */
#define PATCH_ENTRY_CBUFFER_ADVANCE_READ_PTR_EX  0x04009bf9 /* $_cbuffer_advance_read_ptr_ex */
#define PATCH_ENTRY_CBUFFER_GET_READ_ADDRESS_EX  0x04009a1b /* $_cbuffer_get_read_address_ex */
#define PATCH_ENTRY_CBUFFER_GET_READ_ADDRESS_EX_ASM 0x040099fd /* $cbuffer.get_read_address_ex */
#define PATCH_ENTRY_CBUFFER_GET_WRITE_ADDRESS_EX 0x04009a6d /* $_cbuffer_get_write_address_ex */
#define PATCH_ENTRY_CBUFFER_GET_WRITE_ADDRESS_EX_ASM 0x04009a31 /* $cbuffer.get_write_address_ex */
#define PATCH_ENTRY_CBUFFER_CALC_AMOUNT_DATA_EX  0x04009a83 /* $_cbuffer_calc_amount_data_ex */
#define PATCH_ENTRY_CBUFFER_CALC_AMOUNT_SPACE_EX 0x04009ad3 /* $_cbuffer_calc_amount_space_ex */
#define PATCH_ENTRY_CBUFFER_SET_READ_ADDRESS_EX  0x04009b39 /* $_cbuffer_set_read_address_ex */
#define PATCH_ENTRY_CBUFFER_SET_WRITE_ADDRESS_EX 0x04009b55 /* $_cbuffer_set_write_address_ex */
#define PATCH_ENTRY_CBUFFER_COPY_AUDIO_SHIFT_TO_PACKED 0x0400a205 /* $_cbuffer_copy_audio_shift_to_packed */
#define PATCH_ENTRY_CBUFFER_COPY_PACKED_TO_AUDIO_SHIFT 0x0400a2bd /* $_cbuffer_copy_packed_to_audio_shift */
#define PATCH_ENTRY_AOV_REQUEST_CUSTOM_CLOCK     0x04006e85 /* $_aov_request_custom_clock */
#define PATCH_ENTRY_AOV_REQUEST_DEFAULT_CLOCK    0x04006ed7 /* $_aov_request_default_clock */
#define PATCH_ENTRY_AOV_REQUEST_NOTIFY_TRIGGER   0x04006f0f /* $_aov_request_notify_trigger */
#define PATCH_ENTRY_OPMGR_CLIENT_SEND_MESSAGE    0x04005963 /* $_opmgr_op_client_send_message */
#define PATCH_ENTRY_OPMGR_CLIENT_START_OPERATOR  0x0400599d /* $_opmgr_op_client_start_operator */
#define PATCH_ENTRY_OPMGR_CLIENT_STOP_OPERATOR   0x040059cf /* $_opmgr_op_client_stop_operator */
#define PATCH_ENTRY_OPMGR_CLIENT_RESET_OPERATOR  0x04005a01 /* $_opmgr_op_client_reset_operator */
#define PATCH_ENTRY_EXT_BUFFER_CREATE            0x0400820d /* $_ext_buffer_create */
#define PATCH_ENTRY_EXT_BUFFER_DESTROY           0x04008267 /* $_ext_buffer_destroy */
#define PATCH_ENTRY_EXT_AMOUNT_DATA              0x04008317 /* $_ext_buffer_amount_data */
#define PATCH_ENTRY_EXT_AMOUNT_SPACE             0x0400832f /* $_ext_buffer_amount_space */
#define PATCH_ENTRY_EXT_CIRC_READ                0x04008411 /* $_ext_buffer_circ_read */
#define PATCH_ENTRY_EXT_CIRC_WRITE               0x040084bb /* $_ext_buffer_circ_write */
#define PATCH_ENTRY_EXT_GET_READ_OFFSET          0x04008287 /* $_ext_buffer_get_read_offset */
#define PATCH_ENTRY_EXT_SET_READ_OFFSET          0x040082a9 /* $_ext_buffer_set_read_offset */
#define PATCH_ENTRY_EXT_GET_WRITE_OFFSET         0x040082cf /* $_ext_buffer_get_write_offset */
#define PATCH_ENTRY_EXT_SET_WRITE_OFFSET         0x040082f1 /* $_ext_buffer_set_write_offset */
#define PATCH_ENTRY_EXT_RANDOM_ACCESS_READ       0x04008347 /* $_ext_buffer_random_access_read */
#define PATCH_ENTRY_EXT_RANDOM_ACCESS_WRITE      0x040083ad /* $_ext_buffer_random_access_write */
#define PATCH_ENTRY_EXT_DISCARD_DATA             0x040084f7 /* $_ext_buffer_discard_data */
#define PATCH_ENTRY_EXT_BUFFER_PACK              0x04008547 /* $_ext_buffer_pack */
#define PATCH_ENTRY_EXT_BUFFER_UNPACK            0x04008587 /* $_ext_buffer_unpack */
#define PATCH_ENTRY_LOAD_QVA_HANDLE              0x040085cf /* $_load_qva_handle */
#define PATCH_ENTRY_UNLOAD_QVA_HANDLE            0x040085e9 /* $_unload_qva_handle */
#define PATCH_ENTRY_VOICEWAKEUPMULTIKW_PROCESS_DATA 0x040085f5 /* $_VoiceWakeupMultiKW_process_data */
#define PATCH_ENTRY_LOAD_VAD_HANDLE              0x0400861b /* $_load_vad_handle */
#define PATCH_ENTRY_UNLOAD_VAD_HANDLE            0x04008635 /* $_unload_vad_handle */
#define PATCH_ENTRY_VAD400_PROCESS_FUNC_INPUT_IS_CBUFFER_SECURE 0x0400a75f /* $vad400_process_func_input_is_cbuffer_secure */
#define PATCH_ENTRY_AUDIO_PIOS_SET_DIRECTION     0x04008a51 /* $_audio_pios_set_direction */
#define PATCH_ENTRY_AUDIO_PIOS_SET_OUTPUTS       0x04008adf /* $_audio_pios_set_outputs */
#define PATCH_ENTRY_AUDIO_PIOS_GET_INPUTS        0x04008b1b /* $_audio_pios_get_inputs */

#endif /* SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H */
